### ISSUE TITLE
Error when adding additional frontend or hosting nodes -- commit 35383c1

### ISSUE THREAD

**Issue by emuchogu** [OpenNebula/one-deploy#12]
I encountered the following error while adding either front-end or hosting nodes.
```bash
TASK [opennebula.deploy.repository : Install OpenNebula GPG keys] **************************************************************************************************************************************************
Wednesday 04 October 2023  15:06:30 +0300 (0:00:00.070)       0:00:42.667 ***** 
skipping: [node1.lab]
fatal: [node2.lab]: FAILED! => 
  msg: '''dict object'' has no attribute ''content''. ''dict object'' has no attribute ''content'''
```

I managed to resolve the the error by editing the “roles/repository/tasks/main.ym” file
and changing the 'run_once: true' to 'run_once: false' . 
This resolved both adding front-end and hosting nodes.

Bellow are the inventory files I used when trying to add a hosting node:

Installation inventory file:
```yaml
---
all:
  vars:
    ansible_user: root
    ensure_keys_for: [root]
    one_version: "6.6"
    one_pass: opennebulapass
    admin_pubkey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDFtEXeYf6zTey4Rfw92xS1uvPim15bj2yk8FaC6XbHRz/xb0sVHq0bTRqPtLetF+S/0o5lN3Uo6WzfXBFvO2MU80B36ThPcaLXdffq+wg4vmYQr8xI2rBIWPQo+4U9w4t/oHlk3yom1PxguNGeiKN/QIR+m1Vqil5fkzJw3PW/aNIlh6hXOA2N3WRq0pjlsHqprRfxsaveGiesczTSAZpQAEsa2Xg7FnGf4fvLRYxUBwQmvl7aaf+kjLb2HBKe+xX2pHevDmsTnXxOgau7cwyiQtUFddsWBlRmVknQ8zfzhyBT5wvxgFt8sY9mb+yYhDf93aueyK1g1+MFmvL6uti3sweEA0lE4uO0UbaWnWJqHzve9mJ8xNa8NTR64/rh68AHgUY8mrw1LbJ2M6GICGV+llOAZ9evA89rE5jiuV4D/uwmWrqLEamGAi98al9tnmjAd5pYm2lxZe7R1EugEXZ6/acJjrbE9NIoxjYekbjP+Zracn5MzgyT/GW7I3yPHGk= edward@lenovo"

    ds:
      mode: ssh
    vn:
      ext-network:
        managed: true
        template:
          VN_MAD: ovswitch
          BRIDGE: main-bridge
          BRIDGE_TYPE: openvswitch
          AR:
            TYPE: IP4
            IP: 192.168.100.200
            SIZE: 20
          NETWORK_ADDRESS: 192.168.100.0
          NETWORK_MASK: 255.255.255.0
          GATEWAY: 192.168.100.1
          DNS: 192.168.100.1

frontend:
  hosts:
    fe1.lab: { ansible_host: 192.168.100.71 }

node:
  hosts:
    node1.lab: { ansible_host: 192.168.100.71 }

```

Additional node inventory file:
```yaml
---
all:
  vars:
    ansible_user: root
    ensure_keys_for: [root]
    one_version: "6.6"
    one_pass: opennebulapass
    admin_pubkey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDFtEXeYf6zTey4Rfw92xS1uvPim15bj2yk8FaC6XbHRz/xb0sVHq0bTRqPtLetF+S/0o5lN3Uo6WzfXBFvO2MU80B36ThPcaLXdffq+wg4vmYQr8xI2rBIWPQo+4U9w4t/oHlk3yom1PxguNGeiKN/QIR+m1Vqil5fkzJw3PW/aNIlh6hXOA2N3WRq0pjlsHqprRfxsaveGiesczTSAZpQAEsa2Xg7FnGf4fvLRYxUBwQmvl7aaf+kjLb2HBKe+xX2pHevDmsTnXxOgau7cwyiQtUFddsWBlRmVknQ8zfzhyBT5wvxgFt8sY9mb+yYhDf93aueyK1g1+MFmvL6uti3sweEA0lE4uO0UbaWnWJqHzve9mJ8xNa8NTR64/rh68AHgUY8mrw1LbJ2M6GICGV+llOAZ9evA89rE5jiuV4D/uwmWrqLEamGAi98al9tnmjAd5pYm2lxZe7R1EugEXZ6/acJjrbE9NIoxjYekbjP+Zracn5MzgyT/GW7I3yPHGk= edward@lenovo"

    ds:
      mode: ssh
    vn:
      ext-network:
        managed: true
        template:
          VN_MAD: ovswitch
          BRIDGE: main-bridge
          BRIDGE_TYPE: openvswitch
          AR:
            TYPE: IP4
            IP: 192.168.100.200
            SIZE: 20
          NETWORK_ADDRESS: 192.168.100.0
          NETWORK_MASK: 255.255.255.0
          GATEWAY: 192.168.100.1
          DNS: 192.168.100.1

frontend:
  hosts:
    fe1.lab: { ansible_host: 192.168.100.71 }

node:
  hosts:
    node1.lab: { ansible_host: 192.168.100.71 }
    node2.lab: { ansible_host: 192.168.100.72 }
```
