### ISSUE TITLE
IP "move" procedures should handle DHCP logic

### ISSUE THREAD

**Issue by sk4zuzu** [OpenNebula/one-deploy#134]
**Description**
Netplan and NetworkManager IP "move" procedures for bridged networking may result in unpredictable behavior when DHCP is used (for example complete loss of connectivity 😱).

**To Reproduce**
try (VNET config)
```yaml
      admin_net:
        managed: true
        template:
          VN_MAD: bridge
          PHYDEV: eno1
          BRIDGE: br0
```
combined with (Netplan config)
```yaml
network:
    ethernets:
        eth0:
            dhcp4: true
            match:
                macaddress: 54:9F:35:17:E7:90
    version: 2
```

**Expected behavior**
DHCP is detected and handled gracefully.

**Details**
 - Ansible version: N/A
 - Linux OS distro in your cluster: N/A
 - Version: N/A

**Additional context**
🐈 + 🥒 

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)
