### ISSUE TITLE
New augeas-based role to manage oned and kvm configs after deployment

### ISSUE THREAD

**Issue by balazsbme** [OpenNebula/one-deploy#135]
**Description**

At OpenNebula deployment we often need to make configuration changes, specific for an environment or platform in these following configs:
- /etc/one/vmm_exec/vmm_exec_kvm.conf 
- /etc/one/oned.conf
Both are augeas formated config files, so a role that is able to configure them, following similar tasks in a role:

```yaml
- name: Set DEFAULT_CDROM_DEVICE_PREFIX
  augeas:
    lens: oned
    file: /etc/one/oned.conf
    command: set
    path: DEFAULT_CDROM_DEVICE_PREFIX
    value: '"{{ opennebula_server_default_cdrom_device_prefix | string }}"'
  when: opennebula_server_default_cdrom_device_prefix is defined

- name: Configure KVM defaults for RAW
  augeas:
    lens: oned
    file: /etc/one/vmm_exec/vmm_exec_kvm.conf
    command: set
    path: RAW
    value: '"{{ opennebula_server_vmm_kvm_raw }}"'
  when: opennebula_server_vmm_kvm_raw is defined
```

At minimum it should support similar configurations such as the ARM64 specifics, as documented here: https://docs.opennebula.io/6.99/open_cluster_deployment/kvm_node/kvm_driver.html#arm64-specifics 

Preferably the role should be generic enough to be able to configure any field/path of the config files, relying on the augeas module.
