### ISSUE TITLE
Add ceph/dashboard role (feature)

### ISSUE THREAD

**Issue by sk4zuzu** [OpenNebula/one-deploy#22]
1. The Ceph dashboard itself can be easily enabled with such basic steps executed on `mgrs` (for example):

```
ceph config set mgr mgr/dashboard/ssl false
ceph dashboard set-pwd-policy-enabled false

ceph mgr module disable dashboard
ceph mgr module enable dashboard

ceph dashboard ac-user-create oneadmin -i- administrator <<< password
```

and then accessed at http://mgr-ip:8080/.

2. We can reuse Prometheus and Grafana instances we deploy already in OpenNebula. To enable Prometheus module in Ceph:

```
ceph mgr module enable prometheus
```

then Prometheus config needs to be updated like so (the Ceph exporters run on `mgrs` on the `9283/TCP` port):

```yaml
global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'ceph'
    static_configs:
      - targets: ['localhost:9283']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
```

3. Because we deploy our own Prometheus and Grafana instances already, there is little value in using [ceph-dashboard](https://github.com/ceph/ceph-ansible/tree/stable-7.0/roles/ceph-dashboard) role from `ceph-ansible` (which tries to install some components with docker / podman). Ideally all the above config could be implemented in a simple `ceph/dashboard` role in one-deploy :+1: .

:point_up: :relieved:
