### ISSUE TITLE
Add Federation support (feature)

### ISSUE THREAD

**Issue by sk4zuzu** [OpenNebula/one-deploy#30]
Ideally inventory like this one below should deploy 3 HA clusters federated into a single environment :point_up: :relieved: 

```yaml
---
all:
  vars:
    ansible_user: ubuntu
    ensure_keys_for: [ubuntu, root]
    one_pass: asd
    one_version: '6.8'

frontend0:
  hosts:
    n1a1: { ansible_host: 10.2.50.10 }
    n1b1: { ansible_host: 10.2.50.20 }
  vars:
    zone_name: OpenNebula
    one_vip: 10.2.50.111
    one_vip_cidr: 24
    one_vip_if: eth0

frontend1:
  hosts:
    n1a2: { ansible_host: 10.2.50.11 }
    n1b2: { ansible_host: 10.2.50.21 }
  vars:
    one_vip: 10.2.50.122
    one_vip_cidr: 24
    one_vip_if: eth0

frontend2:
  hosts:
    n1a3: { ansible_host: 10.2.50.12 }
    n1b3: { ansible_host: 10.2.50.22 }
  vars:
    one_vip: 10.2.50.133
    one_vip_cidr: 24
    one_vip_if: eth0

frontend:
  children:
    ? frontend0
    ? frontend1
    ? frontend2
```
