### ISSUE TITLE
Shared FS is not mounted automatically for Virtual Frontends

### ISSUE THREAD

**Issue by vickmp** [OpenNebula/one-deploy#46]
**Description**
When a shared storage configuration is added to the inventory of a deployment using a virtual FE configuration (playbook `opennebula.deploy.infra`), the virtual FE is created correctly but the image and file data stores are not configured correctly as no storage devices are mounted on the virtual FE. 

**To Reproduce**
An example inventory is provided below (shared FS is mounted on `/var/lib/one/datastores/`):
```
all:
    ...
    ds:
      mode: shared
      config:
        mounts:
        - type: system
          path: /var/lib/one/datastores
        - type: image
          path: /var/lib/one/datastores
        - type: file
          path: /var/lib/one/datastores
    ...
infra:
  vars:
    os_image_url: https://d24fmfybwxpuhu.cloudfront.net/ubuntu2204-6.8.1-1-20240131.qcow2
    os_image_size: 20G
    infra_bridge: br0
  hosts:
    n1a1: { ansible_host: 10.2.50.10 }
    n1a2: { ansible_host: 10.2.50.11 }
```

**Expected behavior**
The shared FS storage is mounted on each the virtual FE, so as a result, the shared datastores in OpenNebula are correctly configured.

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)
